// 30个主升树埋伏点深扫 — 每标的1agent走完5维,废等回调,cap16排队(退潮树已过滤)
export const meta = { name:'deepscan-30-hot', description:'30主升树埋伏点:每标的1agent走完5维,废等回调', phases:[{title:'埋伏点深扫'}] }
const stocks = [{"ticker": "600505", "name": "金石资源", "env": "萤石氟链上游矿(喂给LiPF6的", "tree": "电动车产品树(终端=买车"}, {"ticker": "002407", "name": "多氟多", "env": "六氟磷酸锂氟链中游(把萤石氟做成", "tree": "电动车产品树(终端=买车"}, {"ticker": "600111", "name": "北方稀土", "env": "重稀土镝铽磁链(喂给EV驱动电机", "tree": "电动车产品树(终端=买车"}, {"ticker": "600516", "name": "方大炭素", "env": "SiC长晶高纯石墨耗材(喂给Si", "tree": "电动车产品树(终端=买车"}, {"ticker": "000657", "name": "中钨高新", "env": "六氟化钨链最上游·钨精矿自给(端", "tree": "AI端侧(AI手机/PC"}, {"ticker": "300684", "name": "中石科技", "env": "端侧VC均热板散热·铜毛细吸液芯", "tree": "AI端侧(AI手机/PC"}, {"ticker": "603938", "name": "三孚股份", "env": "硅碳负极·硅烷气(SiH4)·端", "tree": "AI端侧(AI手机/PC"}, {"ticker": "603191", "name": "望变电气", "env": "取向硅钢-AIDC电源变压器铁芯", "tree": "【AI算力·VR200机"}, {"ticker": "002409", "name": "雅克科技", "env": "HBM前驱体-存储造壳耗材链", "tree": "【AI算力·VR200机"}, {"ticker": "603688", "name": "石英股份", "env": "高纯石英矿-晶圆坩埚/光纤预制棒", "tree": "【AI算力·VR200机"}, {"ticker": "300706", "name": "阿石创", "env": "溅射靶材-芯片/HBM金属化镀膜", "tree": "【AI算力·VR200机"}, {"ticker": "688190", "name": "云路股份", "env": "高频变压器纳米晶/非晶磁芯(固态", "tree": "AI供电树(AI数据中心"}, {"ticker": "600114", "name": "东睦股份", "env": "高频磁粉芯/软磁复合材料(数据中", "tree": "AI供电树(AI数据中心"}, {"ticker": "300263", "name": "隆华科技", "env": "镀膜金属基材-钼靶/钨靶国产替代", "tree": "半导体设备国产化树（产品"}, {"ticker": "688361", "name": "中科飞测", "env": "良率之眼-前道量测/缺陷检测（国", "tree": "半导体设备国产化树（产品"}, {"ticker": "300054", "name": "鼎龙股份", "env": "平坦化耗材-CMP抛光垫国产突破", "tree": "半导体设备国产化树（产品"}, {"ticker": "688019", "name": "安集科技", "env": "平坦化耗材-CMP抛光液+功能性", "tree": "半导体设备国产化树（产品"}, {"ticker": "688122", "name": "西部超导", "env": "机体减重材料-高温合金/钛合金(", "tree": "军工/低空经济树 — 三"}, {"ticker": "300699", "name": "光威复材", "env": "机体减重材料-碳纤维(eVTOL", "tree": "军工/低空经济树 — 三"}, {"ticker": "600893", "name": "航发动力", "env": "推进动力-航空发动机整机(军贸战", "tree": "军工/低空经济树 — 三"}, {"ticker": "300034", "name": "钢研高纳", "env": "机体减重材料-粉末/铸造高温合金", "tree": "军工/低空经济树 — 三"}, {"ticker": "000833", "name": "粤桂股份", "env": "硫精矿→硫化锂源头(硫源溯源)", "tree": "固态电池产品树(终端=2"}, {"ticker": "002741", "name": "光华科技", "env": "硫化锂(Li2S)6N纯化环节(", "tree": "固态电池产品树(终端=2"}, {"ticker": "600206", "name": "有研新材", "env": "高纯硫化锂量产环节(硫化物电解质", "tree": "固态电池产品树(终端=2"}, {"ticker": "301662", "name": "宏工科技", "env": "干法电极前端混料/纤维化设备(干", "tree": "固态电池产品树(终端=2"}, {"ticker": "688375", "name": "国博电子", "env": "星载相控阵T/R组件(载荷价值量", "tree": "商业航天/卫星互联网产品"}, {"ticker": "002046", "name": "国机精工", "env": "火箭/星载精密锻件·特种合金结构", "tree": "商业航天/卫星互联网产品"}, {"ticker": "002025", "name": "航天电器", "env": "星上连接器·线束(贯穿全链每星必", "tree": "商业航天/卫星互联网产品"}, {"ticker": "000969", "name": "安泰科技", "env": "第一壁/偏滤器-钨铜难熔金属(直", "tree": "可控核聚变/核电产品树。"}, {"ticker": "300435", "name": "中泰股份", "env": "杜瓦/深冷低温系统(超导磁体必须", "tree": "可控核聚变/核电产品树。"}]
const VERDICT_SCHEMA = { type:'object', properties:{ decision:{type:'string',enum:['probe','reject','hold']}, sabct:{type:'string'}, size_now:{type:'string',description:'现价建多少仓,禁等回调'}, stop:{type:'string'}, catalyst_date:{type:'string'}, one_line:{type:'string'} }, required:['decision','sabct','size_now','one_line'] }
phase('埋伏点深扫')
log(`30主升树埋伏点·每标的1agent·cap16排队`)
const results = await parallel(stocks.map(c => () => agent(
  `深扫【${c.name} ${c.ticker}】产品树=${c.tree}/环节=${c.env}。走完5维给裁决:\n`+
  `①供给侧Edge:壁垒?真刚需还是概念蹭?中国份额?追到上游矿。\n`+
  `②KillShot:今天没炒是真埋伏还是硬伤(份额假/暴雷/概念蹭)?搜负面。\n`+
  `③定价:现价+PEG+近5-10日累计涨幅(雅克教训:今天没涨不等于没炒透)。没炒透还是已涨一波?\n`+
  `④催化:何时被资金挖到?日期?\n`+
  `⑤现价裁决:严禁等回调。没炒透埋伏=probe现价5到8仓;已炒透(涨停/抛物线)=reject;软=reject。size_now禁写等回调。SABCT(A-门槛)+止损12pct。结论先行。\n`+
  `产品溯源语言。A股数据astock_data_layer/akshare新浪源禁yfinance。禁子agent。快速失败:工具最多2次,2分钟必返回。`,
  { schema:VERDICT_SCHEMA, label:c.name }
))).then(rs=>rs.filter(Boolean))
log(`完成:${results.length}/${stocks.length},probe${results.filter(v=>v.decision==='probe').length}`)
return { count:results.length, decisions:results }
